### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by xaiki** [edipoarg/radar#105]
Generic issue to track performance work for 0.0.3
we're already working on paralelizing initial fetches in #90 but a lot more can be done:
- [ ] cache content browserside
- [ ] split components and lazyload them
- [ ] shrink images
- [ ] remove unused CSS

**Comment by juanigaray** [comment]
Cargado en Trello como deuda técnica: falta definir condiciones proyectadas de hardware y conectividad y hacer pruebas manuales de performance.
