### ISSUE TITLE
-posicionar las fechas del slider en version mobile para que no se pisen con el pop up.

### ISSUE THREAD

**Issue by alexaiconejo** [edipoarg/radar#32]
![WhatsApp Image 2024-01-16 at 13 44 48](https://github.com/edipoarg/radar/assets/139469951/dd9f2ae3-f5b8-4965-9672-4103672f5a9c)

las fechas del slider que aparecen al mover los pines mostrando la fecha seleccionada, se pisan con el pop up de la información del caso elegido en la versión mobile. Creo que la solución sería subir un poco el pop up simplemente.

**Comment by seba-wetzel** [comment]
![Captura desde 2024-01-28 11-28-20](https://github.com/edipoarg/radar/assets/8141029/c815e1c1-82a7-4652-bca4-496b72c0731d)
 El error sigue ocurriendo, solo que tapa menos en algunos casos. 
 El fix de la issue  #46  no aplica en esta.

**Comment by xaiki** [comment]
fixed in 2fe985a
