### ISSUE TITLE
FIX DATES: reparar falla en la fecha de los casos

### ISSUE THREAD

**Issue by alexaiconejo** [edipoarg/radar#34]
La fecha de los casos está bien cargada en el excel, pero en el sitio hay un desfasaje en la fecha, por lo que analizamos pareciera que suma un mes y resta un día a la fecha cargada en el excel.

**Comment by xaiki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modificaciones/mejoras](https://trello.com/c/LKxYhyNx/4-modificaciones-mejoras)

**Comment by xaiki** [comment]
closed by #60
