### ISSUE TITLE
automatizar datos (Cantidad x narrativa) en cuadro de estadísticas

### ISSUE THREAD

**Issue by v-radar** [edipoarg/radar#8]
por ahora los tipos aparecen en los filtros de mapa así que no hace falta repetir en el cuadro de abajo (y entiendo ya están automatizados)
lo que nos interesa desintegrar ahí son las narrativas (considerando que se superponen)

25 ataques a símbolos, lugares y murales: no los encuentro en el excel para modificar 
2 negacionismo y apología a la dictadura: nazismo, antisemitismo y supremacismo tmp los encuentro 
(entiendo que el error ahí está en los : en vez de ; pero la mayoría de los casos implican más de una narrativa)

**Comment by xaiki** [comment]
fixed in cbc468f
